language: rust

cache: cargo

before_script:
  - rustfmt --help 2>/dev/null >/dev/null || rustup component add rustfmt
  - cargo-clippy --help 2>/dev/null >/dev/null || rustup component add clippy || true

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo fmt --all -- --check
  - cargo clippy --help 2>/dev/null >/dev/null && cargo clippy --all --tests -- -D clippy::all
