[package]
name = "sup"
version = "0.1.0"
authors = ["Thomas Preston <thomasmarkpreston@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
